### ISSUE TITLE
[EPIC] Add ingredients to a recipe

### ISSUE THREAD

**Issue by Alexis-PA** [AlexisCro/RecipeManager#14]
## 🖊️ Description
To register a recipe we have to store `has_many` ingredients for a recipe `belongs_to`.

## 🗒️ Actions
To do this we will : 
- [ ] Create a form to add a recipe and after submit render the edit recipe page
- [ ] Add in a partial a form to add an ingredient with hotwire following the doc and Guillaume Briday's tutos
- [ ] Add a button to delete the ingredient following Guillaume Briday's tutos
